spring.application.name=storage-monitor-backend

# ===============================
# Database connection
# ===============================
spring.datasource.url=jdbc:mysql://192.168.60.137:3306/logDB
spring.datasource.username=root
spring.datasource.password=2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

